Working splash page
sanctuarycomputer/sanctucompu pull request #1
Opened 2016-10-12 13:34 UTC by dhunninghake

2016-10-12 14:55 UTC, dhunninghake commented
We had some issues getting Webhook to actually deliver data from the CMS, so for now it's a static build.

2016-10-12 17:07 UTC, keithpops requested changes
Let's also add `main.js` to the the `.gitignore` file since that will be recompiled by webhook anyways

2016-10-12 17:07 UTC, keithpops commented on libs/.firebase.conf.jst
>  }
Might be worth adding this to the `.gitignore` file so we don't commit any keys

2016-10-12 18:05 UTC, hhff commented
👍 agree w/ keith- happy to merge after those comments!

2016-10-14 19:46 UTC, keithpops approved these changes

2016-10-14 19:50 UTC, merged